### ISSUE TITLE
Auto Quiz/ Auto Test.

### ISSUE THREAD

**Issue by ItsKyan69** [GSRHackZ/EdgyBot_Edgenuity_Bot#155]
So before the auto quiz was down about 3 weeks or so ago it would do test perfect! All props for that, but lately the semi automatic quiz script or where it just looks it up and shows you the answer it will be dead wrong. idk if its any different as before but thought i would leave some feedback. much love keep the work up i know it aint easy! <3
also whats the big whoop about no auto assignment i had a script for it before the whole edge rebrand and was wondering what stopped yall from using that code and just updating it over to this. i feel it would add a whole new name to the script as an ALL IN ONE script for edge and not do any work at all. just a thought idk <3

**Comment by GSRHackZ** [comment]
EdgyBot did have support for assignments before the rebrand, but after the rebrand, that feature was patched. It's not as easy as just updating the script. The whole method it used to get answers, XML parsing, no longer works due to Edgenuity patching it. We could possibly introduce the method being used for tests & quizzes to assignments, but that will take time. 

Auto answer was removed because while it may have worked fine on your end, it was heavily criticized by other users. Auto answer is having a slow reintroduction to the bot in order to make it as perfect as can be. We are constantly fixing bugs for it, the semi auto answer that is out right now, in order to make it better before it becomes fully automatic. Fully automatic will require the users to trust that the bot will get them above 65% while they are sound asleep.

Thanks for your feedback 🙏
