### ISSUE TITLE
its not doing the assessments for me 

### ISSUE THREAD

**Issue by jayssen10** [GSRHackZ/EdgyBot_Edgenuity_Bot#270]
it makes me the do the assessments

**Comment by topgovernor1** [comment]
well did you install tampmonkey then it will go as an extention so tap on the little puzzle pisce in the uper right hand side tap on tampermonkey and you should see edgy bot make sure its on then go to edgenutiy and it should ask for you username and password you made for the acount and go in to the class you want to work on and it should  do it job and next time read the insurctions they are there for a reason

**Comment by ITAC85v2** [comment]
Are you saying that it doesn't work on anything at all? If so, is the class in your payment plan?

If it does work but not on certain ones, this is either intentional (lessons named "Assignment" are not supported at this time) or is a bug. Could you clarify, if this is the case, which lessons you are trying to take?

**Comment by GSRHackZ** [comment]
contact 9296737008
