### ISSUE TITLE
Gsrr why are you ghosting we need the edgy botttt!!!!

### ISSUE THREAD

**Issue by cincy513** [GSRHackZ/EdgyBot_Edgenuity_Bot#45]

**Comment by ITAC85v2** [comment]
v3 is work-in-progress. It's currently being worked on by me and GSR. Because an exploit to unlock the coursemap was patched, we are working to support as many assignments as we can.

**Comment by PopDoed** [comment]
Any update on the ETA of v3? Would appreciate knowing if I actually have to start finishing my current course manually, or if im fine to wait for a bit.

**Comment by ITAC85v2** [comment]
Not sure, there is a lot of work to do but I'm not sure how much. I would probably start doing your work manually in the meantime.

**Comment by PopDoed** [comment]
Alright thanks for the heads up.

**Comment by GSRHackZ** [comment]
Yes, Sorry I haven't been active on GitHub and my Instagram was taken down due to a takedown request by Edgenuity for copyright (Edgenuity logo showed in one of the Instagram highlights). Working on version 3.0 of EdgyBot with @ITAC85v2 atm and will try to release it by the end of this month. As @ITAC85v2 said, I would start doing the work manually. If EdgyBot is getting in the way of that (I'm sure it is), deactivate it by clicking the puzzle Icon on the top right of your browser, clicking Tampermonkey and disabling the script.

**Comment by BIODNA** [comment]
GSR whens the new insta coming

**Comment by GSRHackZ** [comment]
Same time as EdgyBot v3.0 release

**Comment by GSRHackZ** [comment]
EdgyBot v3.0 is out.  Couldn't have been done without @ITAC85v2 😊
