### ISSUE TITLE
No AFK option?

### ISSUE THREAD

**Issue by PopDoed** [GSRHackZ/EdgyBot_Edgenuity_Bot#52]
The bot allows me to pick a class and then it will just go on an assignment and say it cant do it instead of having the old option to jjst continue through ungraded assignments.

**Comment by ITAC85v2** [comment]
We're already aware of this, we'll work to add this back but it isn't a priority.

**Comment by GSRHackZ** [comment]
> The bot allows me to pick a class and then it will just go on an assignment and say it cant do it instead of having the old option to jjst continue through ungraded assignments.

Edgenuity patched this option in the last version before v3.0. This feature will most likely not be implemented again as it's currently out of our capabilities. We will see what we can do, but for now consider this feature implementation as impossible

**Comment by zombgabomb** [comment]
Is it even safe to keep the bot going? I checked on a website to see if the bot gives plagiarized answers on things that have to be typed and it said that it's answers are 100% plagiarized.

**Comment by GSRHackZ** [comment]
Those are checked by the computer....
And they don't check for plagiarism, they check for keywords. they are automatically graded.
if you want to be extra careful, maybe because you think your teacher will check the work manually then It's either you use it or you don't. I don't know what else to say.
