### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by noubyg** [GSRHackZ/EdgyBot_Edgenuity_Bot#57]
I have EdgyBot and for some reason its not doing anything, it used to have the gsr logo and the other logo when working on edgenuity but now out of nowhere it stopped, it will auto go to the previously selected class but it will not automate anything it will be as if I had never installed it.

Also I dont know if this is an issue but it happened before the issue above but when it makes me type in the answer in a box for quizzes  it stops the automation for quizzes and it makes me type it in. After I type it in and go to the next question edgybot will stop automation and make me do it myself

**Comment by GTASHAWDOW1211** [comment]
+1 same issue

**Comment by ITAC85v2** [comment]
For the first issue, try reinstalling and reactivating EdgyBot if you haven't already, usually solves issues like these. If this doesn't work, I can't help you unless you provide more info (i.e. which course(s) the issue occurs in, the name of the lesson(s) the issue happens in, etc.).

For the second issue, this isn't easily fixable. None of the devs (including me) have tests or quizzes that contain either checkboxes or short answers rather than the usual multiple choice. What you can do is manually solve those, click on the next question, right-click inside of the test/quiz frame, and click "Reload frame".

**Comment by ishmar231** [comment]
it tells me cant do named classes for all my courses

**Comment by noubyg** [comment]
Uninstalling and reinstalling worked thanks
